FROM python:latest
WORKDIR /app

RUN apt-get update && apt-get -y install libpq-dev gcc

COPY backend/pyproject.toml ./
COPY backend/alembic.ini ./
COPY backend/.env ./

RUN python -m pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry
RUN poetry install

COPY backend/src/ ./src
EXPOSE 8000
