FROM python:latest
WORKDIR /app

RUN apt update -y && apt install -y build-essential libpq-dev

COPY backend/pyproject.toml ./
COPY backend/alembic.ini ./
COPY backend/.env ./

RUN python -m pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry
RUN poetry install

COPY backend/src/ ./src
EXPOSE 8000
