"""Added sessions to Client

Revision ID: 6fcb5bee1878
Revises: 8dca07b860ae
Create Date: 2023-06-20 16:33:22.840335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcb5bee1878'
down_revision = '8dca07b860ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Clients', sa.Column('available_sessions', sa.Float(), nullable=True))
    op.add_column('Clients', sa.Column('used_sessions', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Clients', 'used_sessions')
    op.drop_column('Clients', 'available_sessions')
    # ### end Alembic commands ###
