"""Added is_admin to user

Revision ID: 16a5d9fa1d32
Revises: 7a9652c7816b
Create Date: 2023-03-04 21:33:47.625836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16a5d9fa1d32'
down_revision = '7a9652c7816b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'is_admin')
    # ### end Alembic commands ###
