"""Removed redundant nullable fields

Revision ID: a7e12258543f
Revises: f130f6775535
Create Date: 2023-03-08 13:52:23.198164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7e12258543f'
down_revision = 'f130f6775535'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'telegram_alias',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'telegram_alias',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
