"""AddedModelsAsClasses

Revision ID: f130f6775535
Revises: 16a5d9fa1d32
Create Date: 2023-03-04 23:33:56.102543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f130f6775535'
down_revision = '16a5d9fa1d32'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'telegram_alias',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Users', 'telegram_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'telegram_alias',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Users', 'fullname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
