FROM python:latest
WORKDIR /app

RUN apt update -y && apt install -y build-essential libpq-dev

COPY bot/pyproject.toml ./
COPY bot/.env ./

RUN python -m pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir poetry
RUN poetry install

COPY bot/src/ ./src
